version: '2'
services:
  web1:
    image: docker-demo
    build: .
    ports:
      - 8001:3000
  web2:
    image: docker-demo
    build: .
    ports:
      - 8002:3000
  rproxy:
    image: nginx:1.9.12
    depends_on:
      - web1
      - web2
    links:
      - web1:web1
      - web2:web2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/web.conf
    ports:
      - 8000:8000
